### ISSUE TITLE
Minecraft crashing during different actions in vers. 1.7.10

### ISSUE THREAD

**Issue by cnorris8266** [clienthax/ChocoCraft2#20]
I'm running the correct 1.7.10 version of the mod on the correct forge version, but for some reason certain actions with the chocobo cause it to crash. Firstly, taming them causes the game to crash. Secondly, the chocopedia doesn't actually give me any options on tame chocobo, but instead remains greyed out and unusable. And thirdly, the game crashes as if I were playing multiplayer when I attempt to ride a tamed chocobo. The last one treats it like an online server crash, despite the fact that I play it in single player. 
If you need a screenshot of any of the errors, just reply and I'll post them. It's really easy to replicate but atm it's just late and I don't want to get frustrated again. 
Thanks for the mod and I hope the errors get resolved!

**Comment by cnorris8266** [comment]
This is the crash report when I try to tame them: 

---- Minecraft Crash Report ----
// You're mean.

Time: 4/24/16 8:53 AM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at chococraft.common.network.clientSide.ChocoboTamed.<init>(ChocoboTamed.java:26)
    at chococraft.common.entities.EntityAnimalChocobo.sendTamedUpdate(EntityAnimalChocobo.java:1156)
    at chococraft.common.entities.EntityAnimalChocobo.onGysahlGreenUse(EntityAnimalChocobo.java:616)
    at chococraft.common.entities.EntityAnimalChocobo.func_70085_c(EntityAnimalChocobo.java:561)
    at chococraft.common.entities.EntityChocoboRideable.func_70085_c(EntityChocoboRideable.java:187)
    at chococraft.common.entities.EntityChocobo.func_70085_c(EntityChocobo.java:331)
    at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at chococraft.common.network.clientSide.ChocoboTamed.<init>(ChocoboTamed.java:26)
    at chococraft.common.entities.EntityAnimalChocobo.sendTamedUpdate(EntityAnimalChocobo.java:1156)
    at chococraft.common.entities.EntityAnimalChocobo.onGysahlGreenUse(EntityAnimalChocobo.java:616)
    at chococraft.common.entities.EntityAnimalChocobo.func_70085_c(EntityAnimalChocobo.java:561)
    at chococraft.common.entities.EntityChocoboRideable.func_70085_c(EntityChocoboRideable.java:187)
    at chococraft.common.entities.EntityChocobo.func_70085_c(EntityChocobo.java:331)
    at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:1032)
    at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1126)
    at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:810)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@63db7409
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 221302520 bytes (211 MB) / 601001984 bytes (573 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 7 mods loaded, 7 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCHIJAAAA   chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) 
    UCHIJAAAA   MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
    UCHIJAAAA   httymd{1.1.0} [How to Train Your Minecraft Dragon](HTTYMD-1.7.10-10.13.2.1230F-1.1.0.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10j.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['cm_norris'/256, l='New World', x=222.34, y=66.11, z=283.13]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by cnorris8266** [comment]
When I attempt to ride a tamed, saddled chocobo it tells me it's shutting down internal server and gives me this message: 
**Connection Lost**
A fatal error has occured, this connection is terminated

And gives me the option to go to the title screen.

In this forge profile, I'm running chococraft, DrZhark's Mo'Creatures mod, How to Train Your Minecraft Dragon, and Pam's HarvestCraft.
